---
# See https://github.com/jvautier/project-cli
fullname: jvautier/docker-compose-ghost
description: Docker-compose development stack with ghost.
tags:
  - development
  - docker
  - docker-compose
  - ghost
github:
  has_issues: true
  has_projects: false
  has_wiki: false
