version: "3.7"
services:
  ghost:
    image: ghost:${GHOST_VERSION}-alpine
    environment:
      url: "${GHOST_PROTOCOL}://${GHOST_HOST}:${GHOST_PORT}"
    volumes:
      - ./content:/var/lib/ghost/content
    ports:
      - "8080:2368"
